package TicketToRide.Model;

public class Constants {
	public static enum trainColor{BLUE, RED, GREEN, YELLOW, BLACK};
	public static enum trainCard{PINK,WHITE,BLUE,YELLOW,ORANGE,BLACK,RED,GREEN,RAINBOW};
	public static enum pathColor{PINK,WHITE,BLUE,YELLOW,ORANGE,BLACK,RED,GREEN,GRAY};
	public static enum city{VANCOUVER,SEATTLE,CALGARY,PORTLAND,SAN_FRANCISCO,LOS_ANGELES,
		LAS_VEGAS,SALT_LAKE_CITY,HELENA,WINNIPEG,PHOENIX,SANTA_FE,DENVER,EL_PASO,DULUTH,
		OMAHA,KANSAS_CITY,OKLAHOMA_CITY,DALLAS,HOUSTON,NEW_ORLEANS,LITTLE_ROCK,SAINT_LOUIS,
		CHICAGO,SAULT_ST_MARIE,TORONTO,PITTSBURGH,NASHVILLE,ATLANTA,MIAMI,CHARLESTON,RALEIGH,
		WASHINGTON,NEW_YORK,BOSTON,MONTREAL};
}
