/**
 * TicketToRideGui.java
 * This class represent the main gui of the game. It contains the Swing API code
 * which has been autogenerated to display Swing objects in a JFrame for
 * interacting with the Model classes via the ActionListeners and Control classes.
 */
package TicketToRide.View;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.GridLayout;

import javax.swing.AbstractListModel;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
import javax.swing.JTextArea;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.border.BevelBorder;
import javax.swing.border.EmptyBorder;

import TicketToRide.Model.City;
import TicketToRide.Model.DestinationCard;
import TicketToRide.Model.ParseCSVData;
import TicketToRide.Model.Path;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;

public class TicketToRideGui extends JFrame {

	private JPanel contentPane;

	/**
	 * Launch the application.
	 */
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					TicketToRideGui frame = new TicketToRideGui();
					frame.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

	/**
	 * Create the frame.
	 */
	public TicketToRideGui() {
		setTitle("Ticket To Ride");
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBounds(100, 100, 1300, 700);
		contentPane = new JPanel();
		contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
		contentPane.setLayout(new BorderLayout(0, 0));
		setContentPane(contentPane);

		//ADD SWING GUI ELEMENTS TO JFRAME (AUTOGENERATED)
		JSplitPane spBoard = new JSplitPane();
		contentPane.add(spBoard, BorderLayout.CENTER);

		JPanel pnlBoard = new JPanel();
		spBoard.setRightComponent(pnlBoard);
		pnlBoard.setLayout(new BorderLayout(0, 0));

		JPanel pnlDecks = new JPanel();
		spBoard.setLeftComponent(pnlDecks);
		pnlDecks.setLayout(new GridLayout(8, 1, 0, 0));

		JPanel pnlScoreLogPanel = new JPanel();
		pnlBoard.add(pnlScoreLogPanel, BorderLayout.NORTH);
		pnlScoreLogPanel.setLayout(new GridLayout(0, 2, 0, 0));

		JScrollPane scpScores = new JScrollPane();
		pnlScoreLogPanel.add(scpScores);

		JTextArea txtrScores = new JTextArea();
		txtrScores.setText("scores\n" + "1\n" + "2\n" + "3\n" + "4\n" + "5");
		scpScores.setViewportView(txtrScores);

		JScrollPane scpLog = new JScrollPane();
		pnlScoreLogPanel.add(scpLog);

		JTextArea txtrLog = new JTextArea();
		txtrLog.setText("log\n" + "1\n" + "2\n" + "3\n" + "4\n" + "5");
		scpLog.setViewportView(txtrLog);

		JPanel pnlGraph = new JPanel();
		pnlGraph.setToolTipText("");
		pnlGraph.setBackground(Color.CYAN);
		pnlBoard.add(pnlGraph, BorderLayout.CENTER);
		pnlGraph.setLayout(new BorderLayout(0, 0));

		JPanel pnlCurrentPlayer = new JPanel();
		pnlBoard.add(pnlCurrentPlayer, BorderLayout.SOUTH);
		pnlCurrentPlayer.setLayout(new BorderLayout(0, 0));

		JPanel pnlCurrentPlayerDestCards = new JPanel();
		pnlCurrentPlayer.add(pnlCurrentPlayerDestCards, BorderLayout.WEST);
		pnlCurrentPlayerDestCards.setLayout(new BorderLayout(0, 0));

		JScrollPane scpCurrentPlayerDestCards = new JScrollPane();
		pnlCurrentPlayerDestCards.add(scpCurrentPlayerDestCards, BorderLayout.CENTER);

		JList jlstCurrentPlayerDestCards = new JList();
		jlstCurrentPlayerDestCards.setFont(new Font("Courier New", Font.PLAIN, 11));
		jlstCurrentPlayerDestCards.setVisibleRowCount(3);
		jlstCurrentPlayerDestCards.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		jlstCurrentPlayerDestCards.setModel(new AbstractListModel() {
			String[] values = new String[] { "20:\tLos Angeles->New York",
					"12:\tWinnipeg->Miami", " 7:\tVancouver->Washington",
					" 5:\tCalgary->Atlanta", " 9:\tSeattle->Nashville" };

			public int getSize() {
				return values.length;
			}

			public Object getElementAt(int index) {
				return values[index];
			}
		});
		scpCurrentPlayerDestCards.setViewportView(jlstCurrentPlayerDestCards);

		JPanel pnlCurrentPlayerTrainCards = new JPanel();
		pnlCurrentPlayer.add(pnlCurrentPlayerTrainCards, BorderLayout.CENTER);
		pnlCurrentPlayerTrainCards.setLayout(new GridLayout(1, 12, 0, 0));

		JLabel lblCurrentPlayerTrainCardPink = new JLabel("1");
		lblCurrentPlayerTrainCardPink.setFont(new Font("Tahoma", Font.BOLD, 12));
		lblCurrentPlayerTrainCardPink.setHorizontalAlignment(SwingConstants.CENTER);
		lblCurrentPlayerTrainCardPink.setOpaque(true);
		lblCurrentPlayerTrainCardPink.setBackground(Color.PINK);
		pnlCurrentPlayerTrainCards.add(lblCurrentPlayerTrainCardPink);

		JLabel lblCurrentPlayerTrainCardWhite = new JLabel("2");
		lblCurrentPlayerTrainCardWhite.setFont(new Font("Tahoma", Font.BOLD, 12));
		lblCurrentPlayerTrainCardWhite.setHorizontalAlignment(SwingConstants.CENTER);
		lblCurrentPlayerTrainCardWhite.setBackground(Color.WHITE);
		lblCurrentPlayerTrainCardWhite.setOpaque(true);
		pnlCurrentPlayerTrainCards.add(lblCurrentPlayerTrainCardWhite);

		JLabel lblCurrentPlayerTrainCardBlue = new JLabel("3");
		lblCurrentPlayerTrainCardBlue.setFont(new Font("Tahoma", Font.BOLD, 12));
		lblCurrentPlayerTrainCardBlue.setHorizontalAlignment(SwingConstants.CENTER);
		lblCurrentPlayerTrainCardBlue.setForeground(Color.WHITE);
		lblCurrentPlayerTrainCardBlue.setBackground(Color.BLUE);
		lblCurrentPlayerTrainCardBlue.setOpaque(true);
		pnlCurrentPlayerTrainCards.add(lblCurrentPlayerTrainCardBlue);

		JLabel lblCurrentPlayerTrainCardYellow = new JLabel("4");
		lblCurrentPlayerTrainCardYellow.setFont(new Font("Tahoma", Font.BOLD, 12));
		lblCurrentPlayerTrainCardYellow.setHorizontalAlignment(SwingConstants.CENTER);
		lblCurrentPlayerTrainCardYellow.setBackground(Color.YELLOW);
		lblCurrentPlayerTrainCardYellow.setOpaque(true);
		pnlCurrentPlayerTrainCards.add(lblCurrentPlayerTrainCardYellow);

		JLabel lblCurrentPlayerTrainCardRed = new JLabel("5");
		lblCurrentPlayerTrainCardRed.setForeground(Color.WHITE);
		lblCurrentPlayerTrainCardRed.setFont(new Font("Tahoma", Font.BOLD, 12));
		lblCurrentPlayerTrainCardRed.setHorizontalAlignment(SwingConstants.CENTER);
		lblCurrentPlayerTrainCardRed.setBackground(Color.RED);
		lblCurrentPlayerTrainCardRed.setOpaque(true);
		pnlCurrentPlayerTrainCards.add(lblCurrentPlayerTrainCardRed);

		JLabel lblCurrentPlayerTrainCardBlack = new JLabel("6");
		lblCurrentPlayerTrainCardBlack.setFont(new Font("Tahoma", Font.BOLD, 12));
		lblCurrentPlayerTrainCardBlack.setHorizontalAlignment(SwingConstants.CENTER);
		lblCurrentPlayerTrainCardBlack.setForeground(Color.WHITE);
		lblCurrentPlayerTrainCardBlack.setBackground(Color.BLACK);
		lblCurrentPlayerTrainCardBlack.setOpaque(true);
		pnlCurrentPlayerTrainCards.add(lblCurrentPlayerTrainCardBlack);

		JLabel lblCurrentPlayerTrainCardOrange = new JLabel("7");
		lblCurrentPlayerTrainCardOrange.setFont(new Font("Tahoma", Font.BOLD, 12));
		lblCurrentPlayerTrainCardOrange.setHorizontalAlignment(SwingConstants.CENTER);
		lblCurrentPlayerTrainCardOrange.setForeground(Color.BLACK);
		lblCurrentPlayerTrainCardOrange.setBackground(Color.ORANGE);
		lblCurrentPlayerTrainCardOrange.setOpaque(true);
		pnlCurrentPlayerTrainCards.add(lblCurrentPlayerTrainCardOrange);

		JLabel lblCurrentPlayerTrainCardGreen = new JLabel("8");
		lblCurrentPlayerTrainCardGreen.setFont(new Font("Tahoma", Font.BOLD, 12));
		lblCurrentPlayerTrainCardGreen.setHorizontalAlignment(SwingConstants.CENTER);
		lblCurrentPlayerTrainCardGreen.setBackground(Color.GREEN);
		lblCurrentPlayerTrainCardGreen.setOpaque(true);
		pnlCurrentPlayerTrainCards.add(lblCurrentPlayerTrainCardGreen);

		JLabel lblCurrentPlayerTrainCardRainbow = new JLabel("9");
		lblCurrentPlayerTrainCardRainbow.setFont(new Font("Tahoma", Font.BOLD, 12));
		lblCurrentPlayerTrainCardRainbow.setHorizontalAlignment(SwingConstants.CENTER);
		lblCurrentPlayerTrainCardRainbow.setForeground(Color.WHITE);
		lblCurrentPlayerTrainCardRainbow.setBackground(Color.MAGENTA);
		lblCurrentPlayerTrainCardRainbow.setOpaque(true);
		pnlCurrentPlayerTrainCards.add(lblCurrentPlayerTrainCardRainbow);

		JPanel pnlCurrentPlayerTurnChoices = new JPanel();
		pnlCurrentPlayer.add(pnlCurrentPlayerTurnChoices, BorderLayout.EAST);
		pnlCurrentPlayerTurnChoices.setLayout(new GridLayout(3, 1, 0, 0));

		JButton btnPickTrainCards = new JButton("Pick Train Cards");
		pnlCurrentPlayerTurnChoices.add(btnPickTrainCards);

		JButton btnClaimARoute = new JButton("Claim a Route");
		pnlCurrentPlayerTurnChoices.add(btnClaimARoute);

		JButton btnPickDestCards = new JButton("Pick Destination Cards");
		pnlCurrentPlayerTurnChoices.add(btnPickDestCards);

		JPanel pnlDestCardDeck = new JPanel();
		pnlDecks.add(pnlDestCardDeck);
		pnlDestCardDeck.setLayout(new BorderLayout(0, 0));

		JButton btnDestCardDeck = new JButton("Destination Card Deck");
		pnlDestCardDeck.add(btnDestCardDeck, BorderLayout.CENTER);

		JProgressBar pbrDestCardDeck = new JProgressBar();
		pbrDestCardDeck.setOrientation(SwingConstants.VERTICAL);
		pbrDestCardDeck.setValue(85);
		pnlDestCardDeck.add(pbrDestCardDeck, BorderLayout.EAST);

		JPanel pnlFaceUpTrainCard5 = new JPanel();
		pnlFaceUpTrainCard5.setBorder(new BevelBorder(BevelBorder.RAISED, null, null,
				null, null));
		pnlFaceUpTrainCard5.setBackground(Color.RED);
		pnlDecks.add(pnlFaceUpTrainCard5);

		JPanel pnlFaceUpTrainCard4 = new JPanel();
		pnlFaceUpTrainCard4.setBorder(new BevelBorder(BevelBorder.RAISED, null, null,
				null, null));
		pnlFaceUpTrainCard4.setBackground(Color.ORANGE);
		pnlDecks.add(pnlFaceUpTrainCard4);

		JPanel pnlFaceUpTrainCard3 = new JPanel();
		pnlFaceUpTrainCard3.setBorder(new BevelBorder(BevelBorder.RAISED, null, null,
				null, null));
		pnlFaceUpTrainCard3.setBackground(Color.BLACK);
		pnlDecks.add(pnlFaceUpTrainCard3);

		JPanel pnlFaceUpTrainCard2 = new JPanel();
		pnlFaceUpTrainCard2.setBorder(new BevelBorder(BevelBorder.RAISED, null, null,
				null, null));
		pnlFaceUpTrainCard2.setBackground(Color.BLUE);
		pnlDecks.add(pnlFaceUpTrainCard2);

		JPanel pnlFaceUpTrainCard1 = new JPanel();
		pnlFaceUpTrainCard1.setBorder(new BevelBorder(BevelBorder.RAISED, null, null, null,
				null));
		pnlFaceUpTrainCard1.setBackground(Color.GREEN);
		pnlDecks.add(pnlFaceUpTrainCard1);

		JPanel pnlTrainCardDeck = new JPanel();
		pnlDecks.add(pnlTrainCardDeck);
		pnlTrainCardDeck.setLayout(new BorderLayout(0, 0));

		JProgressBar pbrTrainCardDeck = new JProgressBar();
		pbrTrainCardDeck.setOrientation(SwingConstants.VERTICAL);
		pbrTrainCardDeck.setValue(45);
		pnlTrainCardDeck.add(pbrTrainCardDeck, BorderLayout.EAST);

		JButton btnTrainCardDeck = new JButton("Train Card Deck");
		pnlTrainCardDeck.add(btnTrainCardDeck, BorderLayout.CENTER);

		JPanel pnlCurrentPlayerAvatar = new JPanel();
		pnlDecks.add(pnlCurrentPlayerAvatar);
		pnlCurrentPlayerAvatar.setLayout(new BorderLayout(0, 0));

		JLabel lblPlaceHolderAvatarLabel = new JLabel("[Current Player Image Placeholder]");
		lblPlaceHolderAvatarLabel.setHorizontalAlignment(SwingConstants.CENTER);
		pnlCurrentPlayerAvatar.add(lblPlaceHolderAvatarLabel, BorderLayout.CENTER);
		
		//ActionListeners for Button Clicking Actions
		btnDestCardDeck.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				//TODO:debug action listener code, do not leave in final version-SF
				System.out.println("Destination Card Deck Button");
			}
		});
		
		pnlFaceUpTrainCard5.addMouseListener(new MouseAdapter() {
			public void mousePressed(MouseEvent arg0) {
				//TODO:debug action listener code, do not leave in final version-SF
				System.out.println("Face Up Train Card 5");
			}
		});
		
		pnlFaceUpTrainCard4.addMouseListener(new MouseAdapter() {
			public void mousePressed(MouseEvent e) {
				//TODO:debug action listener code, do not leave in final version-SF
				System.out.println("Face Up Train Card 4");
			}
		});

		pnlFaceUpTrainCard3.addMouseListener(new MouseAdapter() {
			public void mousePressed(MouseEvent e) {
				//TODO:debug action listener code, do not leave in final version-SF
				System.out.println("Face Up Train Card 3");
			}
		});

		pnlFaceUpTrainCard2.addMouseListener(new MouseAdapter() {
			public void mousePressed(MouseEvent e) {
				//TODO:debug action listener code, do not leave in final version-SF
				System.out.println("Face Up Train Card 2");
			}
		});

		pnlFaceUpTrainCard1.addMouseListener(new MouseAdapter() {
			public void mousePressed(MouseEvent e) {
				//TODO:debug action listener code, do not leave in final version-SF
				System.out.println("Face Up Train Card 1");
			}
		});

		btnTrainCardDeck.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				//TODO:debug action listener code, do not leave in final version-SF
				System.out.println("Train Card Deck Button");
			}
		});

		btnPickTrainCards.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				//TODO:debug action listener code, do not leave in final version-SF
				System.out.println("Current Player Pick Train Cards Button");
				ArrayList<City> cityList = ParseCSVData.parseCities();
				for (City c : cityList)
				    System.out.println(c.getCityName() + "\t" + c.getX_val() + "\t" + c.getY_val());
			}
		});

		btnClaimARoute.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				//TODO:debug action listener code, do not leave in final version-SF
				System.out.println("Current Player Claim A Route Button");
				ArrayList<Path> pathList = ParseCSVData.parseRoutes();
				for (Path p : pathList)
				    System.out.println(p.getCity1() + "\t" + p.getCity2() + "\t" + p.getCost() + "\t" + p.getColor());
			}
		});

		btnPickDestCards.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				//TODO:debug action listener code, do not leave in final version-SF
				System.out.println("Current Player Pick Destination Cards Button");
				ArrayList<DestinationCard> destinationCardList = ParseCSVData.parseDestinationCards();
				for (DestinationCard dc : destinationCardList)
				    System.out.println(dc.getCity1() + "\t" + dc.getCity2() + "\t" + dc.getPoint());
			}
		});

	}
	

}
